# http://eslint.org/docs/rules/

root: true
parser: vue-eslint-parser
parserOptions:
  parser: babel-eslint
  sourceType: script
  ecmaVersion: 2015
  allowImportExportEverywhere: true
env:
  es6: true
  node: true
plugins:
  - prettier
extends:
  - eslint:recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:vue/recommended
rules:
  # Prettier
  prettier/prettier:
    - 2
    - singleQuote: true
      trailingComma: all
